from __future__ import annotations

from typing import Any, Dict

MOCK_CASES: Dict[str, Dict[str, Any]] = {
    "ORD123": {
        "order_id": "ORD123",
        "customer_id": "CUST1001",
        "sku": "SKU-778",
        "order_status": "PENDING_DELIVERY",
        "payment_status": "SUCCESS",
        "inventory_status": "AVAILABLE",
        "warehouse_status": "DISPATCHED",
        "carrier_status": "DELAYED",
        "shipping_address_status": "VALID",
        "expected_delivery_date": "2026-10-05",
        "current_delivery_status": "DELAYED",
        "tracking_id": "TRK-12345",
        "warehouse_id": "WH-01",
        "carrier_name": "NorthStar Freight",
        "quantity": 1,
        "priority": "STANDARD",
        "order_value": 120.0,
        "customer_notes": "Customer waiting for delivery.",
        "operational_notes": "Carrier tracking shows a delay in final-mile delivery.",
        "failure_description": "Order ORD123 was expected yesterday but has not arrived. Payment succeeded, inventory was available, and the warehouse dispatched the package, but carrier tracking shows a delivery exception.",
    },
    "ORD124": {
        "order_id": "ORD124",
        "customer_id": "CUST1002",
        "sku": "SKU-201",
        "order_status": "PENDING_FULFILLMENT",
        "payment_status": "SUCCESS",
        "inventory_status": "OUT_OF_STOCK",
        "warehouse_status": "NOT_STARTED",
        "carrier_status": "UNKNOWN",
        "shipping_address_status": "VALID",
        "expected_delivery_date": "2026-10-06",
        "current_delivery_status": "NOT_DISPATCHED",
        "tracking_id": "",
        "warehouse_id": "WH-02",
        "carrier_name": "",
        "quantity": 2,
        "priority": "HIGH",
        "order_value": 75.0,
        "customer_notes": "Customer requests replacement if unavailable.",
        "operational_notes": "Inventory team confirmed no stock is available for the requested SKU.",
        "failure_description": "Order ORD124 has not started fulfillment because the item is unavailable in inventory.",
    },
    "ORD125": {
        "order_id": "ORD125",
        "customer_id": "CUST1003",
        "sku": "SKU-111",
        "order_status": "PAYMENT_REVIEW",
        "payment_status": "FAILED",
        "inventory_status": "AVAILABLE",
        "warehouse_status": "NOT_STARTED",
        "carrier_status": "UNKNOWN",
        "shipping_address_status": "VALID",
        "expected_delivery_date": "2026-10-07",
        "current_delivery_status": "PENDING_PAYMENT",
        "tracking_id": "",
        "warehouse_id": "WH-01",
        "carrier_name": "",
        "quantity": 1,
        "priority": "STANDARD",
        "order_value": 45.0,
        "customer_notes": "Card declined on first attempt.",
        "operational_notes": "Payment authorization failed and no capture was recorded.",
        "failure_description": "Order ORD125 failed because payment authorization was declined and no fulfillment work started.",
    },
    "ORD126": {
        "order_id": "ORD126",
        "customer_id": "CUST1004",
        "sku": "SKU-333",
        "order_status": "PICKING_DELAY",
        "payment_status": "SUCCESS",
        "inventory_status": "AVAILABLE",
        "warehouse_status": "PICKING_DELAYED",
        "carrier_status": "UNKNOWN",
        "shipping_address_status": "VALID",
        "expected_delivery_date": "2026-10-08",
        "current_delivery_status": "PICKING",
        "tracking_id": "",
        "warehouse_id": "WH-03",
        "carrier_name": "",
        "quantity": 3,
        "priority": "STANDARD",
        "order_value": 200.0,
        "customer_notes": "Warehouse delay is affecting promised delivery.",
        "operational_notes": "Picking capacity was constrained and queue length exceeded SLA.",
        "failure_description": "Order ORD126 is delayed by warehouse picking backlog and exceeded the expected processing window.",
    },
    "ORD127": {
        "order_id": "ORD127",
        "customer_id": "CUST1005",
        "sku": "SKU-999",
        "order_status": "UNKNOWN",
        "payment_status": "UNKNOWN",
        "inventory_status": "UNKNOWN",
        "warehouse_status": "UNKNOWN",
        "carrier_status": "UNKNOWN",
        "shipping_address_status": "UNKNOWN",
        "expected_delivery_date": "2026-10-09",
        "current_delivery_status": "UNKNOWN",
        "tracking_id": "",
        "warehouse_id": "",
        "carrier_name": "",
        "quantity": 1,
        "priority": "LOW",
        "order_value": 90.0,
        "customer_notes": "Customer has not responded to delivery confirmation requests.",
        "operational_notes": "Multiple upstream statuses are missing or unconfirmed.",
        "failure_description": "Order ORD127 has unknown payment, inventory, warehouse, and carrier states, making root cause unclear.",
    },
    "ORD128": {
        "order_id": "ORD128",
        "customer_id": "CUST1006",
        "sku": "SKU-560",
        "order_status": "IN_TRANSIT",
        "payment_status": "SUCCESS",
        "inventory_status": "AVAILABLE",
        "warehouse_status": "DISPATCHED",
        "carrier_status": "DELIVERY_ATTEMPTED",
        "shipping_address_status": "INVALID",
        "expected_delivery_date": "2026-10-06",
        "current_delivery_status": "ADDRESS_REJECTED",
        "tracking_id": "TRK-9911",
        "warehouse_id": "WH-05",
        "carrier_name": "RapidParcel",
        "quantity": 1,
        "priority": "HIGH",
        "order_value": 155.0,
        "customer_notes": "Customer reported an incorrect address on the order.",
        "operational_notes": "Carrier attempted delivery but the address was rejected as invalid and must be corrected.",
        "failure_description": "Order ORD128 was dispatched and carrier attempted delivery, but the shipping address is invalid and the delivery failed.",
    },
}


def get_mock_order(order_id: str) -> Dict[str, Any]:
    case = MOCK_CASES.get(order_id)
    if not case:
        return {
            "order_id": order_id,
            "order_status": "UNKNOWN",
            "customer_id": "UNKNOWN",
            "sku": "UNKNOWN",
            "payment_status": "UNKNOWN",
            "inventory_status": "UNKNOWN",
            "warehouse_status": "UNKNOWN",
            "carrier_status": "UNKNOWN",
            "shipping_address_status": "UNKNOWN",
            "expected_delivery_date": "UNKNOWN",
            "current_delivery_status": "UNKNOWN",
            "tracking_id": "",
            "warehouse_id": "",
            "carrier_name": "",
            "quantity": 0,
            "priority": "UNKNOWN",
            "order_value": 0.0,
        }
    return case


def get_order_status_snapshot(order_id: str) -> Dict[str, Any]:
    data = get_mock_order(order_id)
    return {
        "order_id": data.get("order_id"),
        "order_status": data.get("order_status"),
        "payment_status": data.get("payment_status"),
        "inventory_status": data.get("inventory_status"),
        "warehouse_status": data.get("warehouse_status"),
        "carrier_status": data.get("carrier_status"),
        "shipping_address_status": data.get("shipping_address_status"),
        "expected_delivery_date": data.get("expected_delivery_date"),
        "current_delivery_status": data.get("current_delivery_status"),
    }
