PROMPT_REGISTRY = {
    "supervisor": {
        "prompt_id": "supervisor_v1",
        "name": "Supervisor",
        "version": "1.0",
        "description": "Orchestrates the investigation and final decision.",
        "template": "Review the fulfillment case, decide required agents, and identify whether the case is straightforward or requires deeper investigation.",
        "input_variables": ["order_id", "failure_description", "selected_agents"],
        "model_settings": {"temperature": 0.1, "max_tokens": 800},
        "status": "active",
    },
    "planner": {
        "prompt_id": "planner_v1",
        "name": "Planner",
        "version": "1.0",
        "description": "Creates a structured fulfillment investigation plan.",
        "template": "Create a plan to investigate the order failure using the minimal required evidence.",
        "input_variables": ["order_id", "request", "risk_level"],
        "model_settings": {"temperature": 0.1, "max_tokens": 700},
        "status": "active",
    },
    "router": {
        "prompt_id": "router_v1",
        "name": "Router",
        "version": "1.0",
        "description": "Selects specialized agents based on operational evidence.",
        "template": "Choose the most relevant fulfillment agents based on the known status and evidence.",
        "input_variables": ["order_id", "failure_description", "status_summary"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "order": {
        "prompt_id": "order_v1",
        "name": "Order",
        "version": "1.0",
        "description": "Investigates order-level anomalies.",
        "template": "Review the order lifecycle for delivery timing, status anomalies, and lifecycle issues.",
        "input_variables": ["order_id", "order_data"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "inventory": {
        "prompt_id": "inventory_v1",
        "name": "Inventory",
        "version": "1.0",
        "description": "Reviews stock, reservations, and availability evidence.",
        "template": "Assess whether inventory shortage or reservation failure explains the order disruption.",
        "input_variables": ["sku", "inventory_data"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "payment": {
        "prompt_id": "payment_v1",
        "name": "Payment",
        "version": "1.0",
        "description": "Checks authorization, capture, and payment failure status.",
        "template": "Verify whether payment failure caused the fulfillment issue.",
        "input_variables": ["order_id", "payment_data"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "warehouse": {
        "prompt_id": "warehouse_v1",
        "name": "Warehouse",
        "version": "1.0",
        "description": "Reviews warehouse queue, processing, and exceptions.",
        "template": "Determine if warehouse processing delay caused the order to fail.",
        "input_variables": ["warehouse_data"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "carrier": {
        "prompt_id": "carrier_v1",
        "name": "Carrier",
        "version": "1.0",
        "description": "Investigates shipment, tracking, and delivery exceptions.",
        "template": "Assess whether a carrier issue is preventing delivery.",
        "input_variables": ["carrier_data", "tracking_id"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "address": {
        "prompt_id": "address_v1",
        "name": "Address",
        "version": "1.0",
        "description": "Investigates shipping-address validation, corrections, or rejects.",
        "template": "Check whether invalid or undeliverable address information explains the failure.",
        "input_variables": ["address_data"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "policy": {
        "prompt_id": "policy_v1",
        "name": "Policy",
        "version": "1.0",
        "description": "Retrieves policy evidence relevant to a specific fulfillment issue.",
        "template": "Retrieve policy evidence and compliance rules relevant to the case.",
        "input_variables": ["failure_description", "order_id"],
        "model_settings": {"temperature": 0.1, "max_tokens": 700},
        "status": "active",
    },
    "classification": {
        "prompt_id": "classification_v1",
        "name": "Classification",
        "version": "1.0",
        "description": "Combines all evidence into a reasoned classification.",
        "template": "Synthesize operational findings into a single failure reason and confidence score.",
        "input_variables": ["agent_findings", "retrieved_context", "order_data"],
        "model_settings": {"temperature": 0.1, "max_tokens": 800},
        "status": "active",
    },
    "critic": {
        "prompt_id": "critic_v1",
        "name": "Critic",
        "version": "1.0",
        "description": "Challenges the classification and highlights missing or contradictory evidence.",
        "template": "Review the proposed classification for contradictions, missing data, and false certainty.",
        "input_variables": ["classification", "agent_findings"],
        "model_settings": {"temperature": 0.1, "max_tokens": 700},
        "status": "active",
    },
    "reviewer": {
        "prompt_id": "reviewer_v1",
        "name": "Reviewer",
        "version": "1.0",
        "description": "Reviews the classification, critic feedback, and evidence quality.",
        "template": "Decide whether the classification should be approved, revised, or escalated to a human reviewer.",
        "input_variables": ["classification", "critic_result", "policy_context"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "validator": {
        "prompt_id": "validator_v1",
        "name": "Validator",
        "version": "1.0",
        "description": "Validates output structure, taxonomy, and evidence quality.",
        "template": "Check that the final output respects the allowed taxonomy and evidence rules.",
        "input_variables": ["classification", "evidence"],
        "model_settings": {"temperature": 0.1, "max_tokens": 600},
        "status": "active",
    },
    "response": {
        "prompt_id": "response_v1",
        "name": "Response",
        "version": "1.0",
        "description": "Produces the final human-readable response.",
        "template": "Summarize the final decision, evidence, and recommended next steps clearly.",
        "input_variables": ["failure_reason", "decision", "recommended_action"],
        "model_settings": {"temperature": 0.2, "max_tokens": 700},
        "status": "active",
    },
    "security": {
        "prompt_id": "security_v1",
        "name": "Security",
        "version": "1.0",
        "description": "Applies prompt injection and content-safety guardrails.",
        "template": "Scan all inputs and outputs for unsafe prompts, PII, or secret leakage.",
        "input_variables": ["request", "retrieved_context"],
        "model_settings": {"temperature": 0.0, "max_tokens": 400},
        "status": "active",
    },
}
